### ISSUE TITLE
[ISSUE_01] - [DOCUMENTATION] - Regra de Negócio do CSU01 não indica quais notas são aceitas

### ISSUE THREAD

**Issue by zejsneto** [zejsneto/Lab-Ticket-Machine-Corrigido#1]
### Descrição
A Regra de Negócio do CSU01 (Inserir dinheiro) não indica quais notas são aceitas pelo sistema.

### Passos para reproduzir:
1.  O Cliente insere uma nota de papelmoeda.
2. O Sistema mostra uma mensagem informando para o Cliente aguardar alguns instantes.
3. O Sistema valida a nota de papel-moeda inserida.
4. O Sistema adiciona o valor ao saldo disponível.
5. O Sistema informa que a nota de papelmoeda foi aceita.
6. O sistema informa o saldo atual. Caso de Uso é encerrado.

### Comportamento esperado:
O sistema exibe as notas de papel-moeda aceitas por ele.

### Comportamento atual:
O sistema não exibe as notas de papel-moeda aceitas por ele.

**Comment by lucasgp147** [comment]
Por se tratar de um ISSUE de documentação não tem código para pull request porém será corrigido no próximo material.
