### ISSUE TITLE
[ISSUE_06] - [CODE] - Valor do Ticket é igual ao valor do Saldo por erro de código

### ISSUE THREAD

**Issue by zejsneto** [zejsneto/Lab-Ticket-Machine-Corrigido#12]
### Descrição
O valor exibido para o "valor do ticket" e "saldo" está incorreto, ambos mostram tm.getSaldo() na linha 25.

### Passos para localizar o código:
1. Abra o arquivo 'Main.class' 
3. Vá até a linha 25 e note o erro.

### Comportamento esperado:
O valor exibido para o "valor do ticket" e "saldo" está correto pois cada um esta usando seu proprio 'get'.

### Comportamento atual:
O valor exibido para o "valor do ticket" é igual ao valor do "saldo".

**Comment by lucasgp147** [comment]
Resolvido e enviado para main
