### ISSUE TITLE
[ISSUE_08] - [CODE] - A impressão do valor da cédula é feita duas vezes

### ISSUE THREAD

**Issue by zejsneto** [zejsneto/Lab-Ticket-Machine-Corrigido#18]
### Descrição
No método 'Main.class', A impressão do valor da cédula é feita duas vezes.

### Passos para localizar o código:
1. Abra o arquivo 'Main.class' 
3. Vá até a linha 66 e note o erro.

### Comportamento esperado:
A impressão do valor da cédula é feita apenas uma vez.

### Comportamento atual:
A impressão do valor da cédula é feita duas vezes.

**Comment by lucasgp147** [comment]
avaliado e enviado para a main
