### ISSUE TITLE
[Issue 09] -  Laço for deveria verificar se ret é null e não o contrário

### ISSUE THREAD

**Issue by zejsneto** [zejsneto/Lab-Ticket-Machine-Corrigido#22]
### Descrição
No método next() no arquivo 'Troco$TrocoIterator.class', o laço for deveria verificar se ret é null, mas a condição está invertida.

### Passos para localizar o código:
1. Abra o arquivo 'Troco$TrocoIterator.class' 
3. Vá até a linha 27 e note o erro.

### Comportamento esperado:
Laço for verifica se ret é null.

### Comportamento atual:
Laço for verifica se ret não é null.

**Comment by lucasgp147** [comment]
avaliado e enviado para a main
