### ISSUE TITLE
[ISSUE_10] - [CODE] - Método getIterator() está passando dois parâmetros

### ISSUE THREAD

**Issue by zejsneto** [zejsneto/Lab-Ticket-Machine-Corrigido#25]
### Descrição
O método 'getIterator()' está passando dois parâmetros para o construtor na classe 'Troco', na linha 43.

### Passos para localizar o código:
1. Abra o arquivo 'Troco.class' 
3. Vá até a linha 43 e note o erro.

### Comportamento esperado:
O método 'getIterator()' está passando 1 parâmetro para o construtor.

### Comportamento atual:
O método 'getIterator()' está passando dois parâmetros para o construtor.

**Comment by lucasgp147** [comment]
avaliado e enviado para a main
