### ISSUE TITLE
[ISSUE_13] - [CODE] - Troco$TrocoIterator, é necessário alterar o mét.

### ISSUE THREAD

**Issue by lucasgp147** [zejsneto/Lab-Ticket-Machine-Corrigido#28]
metodo remove()

Localização:
Classe Troco$TrocoIterator, método remove().

Comportamento Esperado:

O método remove() deveria lançar uma exceção UnsupportedOperationException, indicando que a operação de remoção não é suportada. Comportamento Atual: O método remove() atualmente chama next(), o que altera o estado do iterator e não representa o comportamento adequado para um método de remoção não implementado.

**Comment by zejsneto** [comment]
Avaliado e feito o merge para a Main.
