### ISSUE TITLE
[ISSUE_11] - [CODE] - Saldo da TicketMachine não é zerado após o troco ser gerado

### ISSUE THREAD

**Issue by zejsneto** [zejsneto/Lab-Ticket-Machine-Corrigido#29]
### Descrição
No método imprimir(), o saldo da TicketMachine não é zerado após o troco ser gerado e o ticket ser impresso.

### Passos para localizar o código:
1. Abra o arquivo 'TicketMachine.class' 
3. Vá até a linha 46 em diante e note o erro.

### Comportamento esperado:
O saldo da TicketMachine é zerado após o troco ser gerado e o ticket ser impresso.

### Comportamento atual:
O saldo da TicketMachine não é zerado após o troco ser gerado e o ticket ser impresso.

**Comment by lucasgp147** [comment]
Resolvido e enviado para a main
