### ISSUE TITLE
[ISSUE_03] - [DOCUMENTATION] - Pré-condição do CSU03 não informa que é necessário ter saldo disponível no sistema para poder emitir troco

### ISSUE THREAD

**Issue by zejsneto** [zejsneto/Lab-Ticket-Machine-Corrigido#3]
### Descrição
A Pré-condição do CSU03 (Solicitar troco) não informa que é necessário ter saldo disponível no sistema para poder emitir o troco.

### Passos para reproduzir:
1.  O Cliente solicita devolução do saldo restante como troco.
2. O Sistema verifica o saldo e devolve a quantidade do saldo em notas de papelmoeda.
3. O Sistema zera o valor do saldo.
4. O sistema informa o saldo atual. Caso de Uso é encerrado.

### Comportamento esperado:
O sistema informa que é necessário ter saldo disponível para emitir o troco.

### Comportamento atual:
O sistema não informa que é necessário ter saldo disponível para emitir o troco.

**Comment by lucasgp147** [comment]
Por se tratar de um ISSUE de documentação não tem código para pull request porém será corrigido no próximo material.
