### ISSUE TITLE
[ISSUE_15] - [CODE] - No método inserir, o laço for compara sempre o índice 1 do array papelMoeda

### ISSUE THREAD

**Issue by zejsneto** [zejsneto/Lab-Ticket-Machine-Corrigido#32]
### Descrição
Variável 'count' não é zerada após verificar tipo de nota em 'Troco.class'.

### Passos para localizar o código:
1. Abra o arquivo 'Troco.class' 
3. Vá até a linha 11 (por exemplo) e note o erro.

### Comportamento esperado:
Variável 'count' é zerada após verificar tipo de nota em 'Troco.class'.

### Comportamento atual:
Variável 'count' não é zerada após verificar tipo de nota em 'Troco.class'.

**Comment by lucasgp147** [comment]
Resolvido e enviado para a main
