### ISSUE TITLE
[ISSUE_04] - [CODE] - No método inserir, o laço for compara sempre o índice 1 do array papelMoeda

### ISSUE THREAD

**Issue by zejsneto** [zejsneto/Lab-Ticket-Machine-Corrigido#4]
### Descrição
No método inserir no arquivo 'TicketMachine.class', o laço for compara sempre o índice 1 do array papelMoeda.

### Passos para localizar o código:
1. Abra o arquivo 'TicketMachine.class' 
2. Vá até o método 'Inserir()' na linha 18
3. Vá até a linha 22 e note o erro

### Comportamento esperado:
No método inserir, o laço for compara sempre o índice i do array papelMoeda.

### Comportamento atual:
No método inserir, o laço for compara sempre o índice 1 do array papelMoeda.

**Comment by lucasgp147** [comment]
Código avaliado, merge feito para a main.
