### ISSUE TITLE
[ISSUE_05] - [CODE] - Exibido TocketMachine ao invés de TicketMachine na Main

### ISSUE THREAD

**Issue by zejsneto** [zejsneto/Lab-Ticket-Machine-Corrigido#7]
### Descrição
No arquivo Main.class, é exibido o nome do software como 'TocketMachine' ao invés de 'TicketMachine'.

### Passos para localizar o código:
1. Abra o arquivo 'Main.class' 
3. Vá até a linha 23 e note o erro.

### Comportamento esperado:
No arquivo Main.class, é exibido o nome do software como 'TicketMachine'.

### Comportamento atual:
No arquivo Main.class, é exibido o nome do software como 'TocketMachine'.

**Comment by lucasgp147** [comment]
Avaliado e Enviado para a main
